### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by jetyang98** [SMILELab-FL/FedLab#218]
你好，我在 FedLab/examples/standalone-mnist/ 目录下，运行 `bash launch_eg.sh` 会报如下错误：
```
Traceback (most recent call last):
  File "standalone.py", line 15, in <module>
    from fedlab.core.client.serial_trainer import SubsetSerialTrainer
  File "../../fedlab/core/__init__.py", line 15, in <module>
    from . import client, server, communicator
  File "../../fedlab/core/client/__init__.py", line 19, in <module>
    from .trainer import ClientTrainer, SGDClientTrainer
  File "../../fedlab/core/client/trainer.py", line 23, in <module>
    class ClientTrainer(ModelMaintainer):
  File "../../fedlab/core/client/trainer.py", line 43, in ClientTrainer
    def uplink_package(self) -> list[torch.Tensor]:
TypeError: 'type' object is not subscriptable
```
Python 版本为 3.7.13。
我使用 VSCode 打开 trainer.py 文件后，会出现以下提示：
```
Subscript for class "list" will generate runtime exception; enclose type annotation in quotes Pylance
```
如果我把代码改为 `def uplink_package(self) -> list([torch.Tensor]):` VSCode 就不报错了。
请问我在运行代码时出错的原因是 VSCode 所提示的这样吗？

**Comment by Zengdun-cs** [comment]
是的，这里是一个语法错误，确实是这样修复。
感谢提醒。

**Comment by Zengdun-cs** [comment]
测试了一下，我这里没有报错。
这里是一个返回类型指示，uplink_package需要返回一个内容是tensor的列表。

**Comment by Zengdun-cs** [comment]
收到反馈，这个错误好像还是存在。
我再试着修复下。

**Comment by Zengdun-cs** [comment]
如果是跑fedlab-benchmarks下的代码，注意下版本号，v1.2.0接口改了很多，所以与1.1.*版本不兼容。

**Comment by AgentDS** [comment]
能说一下用的python的版本吗，我们怀疑可能是类型检查导致的。

**Comment by Zengdun-cs** [comment]
检查后发现应该是python版本不同导致语法错误，下个版本会修正。
感谢反馈。
