### ISSUE TITLE
Standalone.py Cuda Error

### ISSUE THREAD

**Issue by sltTn** [SMILELab-FL/FedLab#352]
**Describe the bug**
Hi,
Thank you so much for your project, I was wondering ask you something. I am trying to know the fed lab project and work with than, so I started by working on standalone.py base on you tutorial.
after running, I faced this error:

(base) nasim@Nasims-MacBook-Air standalone-mnist % python standalone.py --total_clients 100 --com_round 3 --sample_ratio 0.1 --batch_size 100 --epochs 5 --lr 0.02
14:23:01 - numexpr.utils - INFO - NumExpr defaulting to 8 threads.
Traceback (most recent call last):
  File "/Users/nasim/Downloads/FedLab-master/examples/standalone-mnist/standalone.py", line 40, in <module>
    handler = SyncServerHandler(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/nasim/anaconda3/lib/python3.11/site-packages/fedlab/contrib/algorithm/basic_server.py", line 49, in __init__
    super(SyncServerHandler, self).__init__(model, cuda, device)
  File "/Users/nasim/anaconda3/lib/python3.11/site-packages/fedlab/core/server/handler.py", line 40, in __init__
    super().__init__(model, cuda, device)
  File "/Users/nasim/anaconda3/lib/python3.11/site-packages/fedlab/core/model_maintainer.py", line 42, in __init__
    self.device = get_best_gpu()
                  ^^^^^^^^^^^^^^
  File "/Users/nasim/anaconda3/lib/python3.11/site-packages/fedlab/utils/functional.py", line 123, in get_best_gpu
    assert torch.cuda.is_available()
AssertionError

**Additional context**
I am trying to run it on Mac, and using VS Code to run the code.

Best Regards,
Nasim

**Comment by dunzeng** [comment]
Mac does not support GPU mode. You can modify ```cuda=False``` to use CPU mode.

For example, please see line 45 of [script](https://github.com/SMILELab-FL/FedLab/blob/master/examples/standalone-mnist/standalone.py) and set ```cuda=False``` for local trainer. 

I think this can solve your issue.
